---
galaxy_info:
  author: Ansible Cloud Content Team (@redhat-cop)
  description: Deploy a custom Windows template from a content library and apply customizations
  company: Red Hat, Inc.
  license: GPL-3.0-or-later
  min_ansible_version: "2.13"
  galaxy_tags:
    - infrastructure
    - vmware

dependencies: []
