---
info_hostname: "{{ vmware_ops_collection_hostname }}"
info_username: "{{ vmware_ops_collection_username }}"
info_password: "{{ vmware_ops_collection_password }}"
info_validate_certs: "{{ vmware_ops_collection_validate_certs | default(true) }}"
info_port: "{{ vmware_ops_collection_port }}"

info_expose_outputs_as_variable: true
info_hostport: "{{ info_hostname + ':' + info_port if info_port is defined else info_hostname }}"

# Appliance
info_appliance_gather: all
info_appliance_file: "/tmp/vmware_ops_info_appliance"

# Cluster
info_datacenters: []
info_cluster_file: "/tmp/vmware_ops_info_cluster"

# Guest
info_guest_file: "/tmp/vmware_ops_info_guest"

# License
info_license_file: "/tmp/vmware_ops_info_license"

# Storage
info_storage_file: "/tmp/vmware_ops_info_storage"

# Enable
info_guest: false
info_cluster: false
info_license: false
info_storage: false
info_appliance: false
