---
deploy_custom_windows_template_hostname: "{{ vmware_ops_collection_hostname }}"
deploy_custom_windows_template_username: "{{ vmware_ops_collection_username }}"
deploy_custom_windows_template_password: "{{ vmware_ops_collection_password }}"
deploy_custom_windows_template_validate_certs: "{{ vmware_ops_collection_validate_certs }}"
deploy_custom_windows_template_port: "{{ vmware_ops_collection_port }}"

deploy_custom_windows_template_proxy_host: "{{ vmware_ops_collection_proxy_host }}"
deploy_custom_windows_template_proxy_port: "{{ vmware_ops_collection_proxy_port }}"

deploy_custom_windows_template_auto_logon: true
deploy_custom_windows_template_auto_logon_count: 1
deploy_custom_windows_template_force_customization: true
